### ISSUE TITLE
Add cUseful to libs

### ISSUE THREAD

**Issue by kospl** [oshliaer/google-apps-script-awesome-list#20]
https://github.com/brucemcpherson/cUseful

**Comment by oshliaer** [comment]
I'm looking for the description of the library. It seems this should be like 'various dependency free useful functions' [#](https://script.googleusercontent.com/macros/echo?user_content_key=VblToac81yPpoq-cfdh2MsujxV1bOrv-7waB2anLDzKtzNcvaFDE3TKCuQlpIE0sX9Txr_CGhD6RGtH_tftpTPvFEMKtzxPRm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnGrmXbj0UZ42F7JMOKWp7xmXQUOGAGCJXzrzTebdg7DrvN7sgVkOBaxTMUhTNAZ6xycfNc2fO4hD&lib=MqlPsVRCxXIIF1J7TgkeSqai_d-phDA33).

I'm going to add this to 'Utility'.
