### ISSUE TITLE
Small repository of examples

### ISSUE THREAD

**Issue by derekantrican** [oshliaer/google-apps-script-awesome-list#21]
I have created a GitHub repository where I'm starting to upload my GAS scripts that people can reference for examples. Probably the most helpful part is that I'm putting in some for external APIs (Trello, Slack, Twilio). It's small at the moment, but there's more to come.

Wondering if it'd be useful to add in the "Snippets and assorted" section of the README

https://github.com/derekantrican/Google-Apps-Script-Library

**Comment by oshliaer** [comment]
Hi @derekantrican 

Thanks for your suggestion! I'd like position this to 'Snippets and assorted'.
